version: '3.3'

services:
  frontend:
    image: davidfasel/alertsdisplayapp:latest-amd64
    container_name: frontend_c
    ports:
      - "3000:3000"  # Update if different external/internal ports are required
    networks:
      - mynetwork
    restart: unless-stopped

  backend:
    image: davidfasel/backend:latest-amd64
    container_name: backend_c
    ports:
      - "6543:6543"  # Update if different external/internal ports are required
    networks:
      - mynetwork
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: db_c
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data  # Create this volume folder for persistent DB storage
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    env_file:
      - ./backend/.env.postgres

volumes:
      db_data:

networks:
  mynetwork:
    driver: bridge
