"""Initial migration.

Revision ID: 596735f9be9d
Revises: 
Create Date: 2024-12-19 17:04:31.157045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596735f9be9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('dateText', sa.String(), nullable=True),
    sa.Column('parsedDate', sa.String(), nullable=True),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stop_id'], ['stop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('stop')
    # ### end Alembic commands ###
